# Swagger
springdoc.swagger-ui.path=/swagger
springdoc.enable-hateoas=false

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:gestor;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.h2.console.settings.web-allow-others=false

# Configuracao JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Spring Security
api.security.token.secret=${JWT_SECRET:my-secret-key}
api.security.token.expiration=${JWT_EXPIRATION:2}
api.security.token.issuer=${JWT_ISSUER:supergestor-api}
api.security.refresh.expiration=${JWT_REFRESH_EXPIRATION:60}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=when_authorized
management.endpoint.health.probes.enabled=true
springdoc.show-actuator=true

# Admin user
app.admin.username=admin
app.admin.password=senhaSuperSecreta456
app.admin.nome=Administrador Padrão
app.admin.email=admin@meuapp.com
app.admin.cpf=123456789

# Logs
logging.file.path=/var/log/super-gestor
logging.file.name=meu-app.log

spring.flyway.enabled=false

spring.cache.type=simple
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration